CREATE TABLE assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT
    , uuid VARCHAR(36) NOT NULL
    , name VARCHAR(255) NOT NULL
    , hash VARCHAR(64) NOT NULL
    , mime VARCHAR(64) NOT NULL
    , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS assets_idx_uuid ON assets (uuid);
CREATE INDEX IF NOT EXISTS assets_idx_hash ON assets (hash);
